#!/usr/bin/env bash
# anvil/learn — draft a MEMORY.md-pasteable markdown chunk of high-confidence
# learnings recorded since a given date. Sister to /learn export, but
# opinionated toward MEMORY.md promotion:
#   - Defaults to --min-confidence high (export defaults to medium).
#   - Output is grouped first by `type:decision` (most durable), then by
#     remaining types, so decisions land at the top of the paste.
#   - Includes a "Pasteable bullet" line per entry shaped to match the
#     project + feedback memory-line style.
#
# Usage:
#   learn-promote.sh --since <YYYY-MM-DD> [--min-confidence <low|medium|high>] [--type <type>]
#
# Defaults:
#   --min-confidence high
#
# Use case: at the end of a sprint, operator wants the top 5-10 durable
# learnings to migrate into ~/.claude/projects/<...>/memory/MEMORY.md (or
# equivalent). This emits a paste-ready block; operator picks which lines
# to keep.

set -u

# Resolve ANVIL_ROOT (mirrors skills/learn/scripts/learn-export.sh).
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
if [ -z "${ANVIL_ROOT:-}" ]; then
  _av_cfg="$SCRIPT_DIR/../../../anvil-config.sh"
  if [ -f "$_av_cfg" ]; then
    # shellcheck source=/dev/null
    . "$_av_cfg"
  fi
  unset _av_cfg
fi
if [ -z "${ANVIL_ROOT:-}" ] && [ -f "${ANVIL_HOME:-${CLAUDE_HOME:-${HOME}/.claude}}/anvil-config.sh" ]; then
  # shellcheck source=/dev/null
  . "${ANVIL_HOME:-${CLAUDE_HOME:-${HOME}/.claude}}/anvil-config.sh"
fi
if [ -z "${ANVIL_ROOT:-}" ]; then
  ANVIL_ROOT="$(cd "$SCRIPT_DIR/../../.." && pwd)"
fi
# shellcheck source=/dev/null
. "$ANVIL_ROOT/shared/lib.sh"

usage() {
  echo "usage: learn-promote.sh --since <YYYY-MM-DD> [--min-confidence <low|medium|high>] [--type <type>]" >&2
  echo "  --since is required" >&2
  echo "  --min-confidence defaults to high (use 'medium' to widen)" >&2
}

SINCE=""
MIN_CONF="high"
TYPE_FILTER=""

while [ $# -gt 0 ]; do
  case "$1" in
    --since)          SINCE="${2:-}"; shift 2;;
    --min-confidence) MIN_CONF="${2:-}"; shift 2;;
    --type)           TYPE_FILTER="${2:-}"; shift 2;;
    -h|--help)        usage; exit 0;;
    *)                av_fail "unknown arg: $1"; usage; exit 1;;
  esac
done

if [ -z "$SINCE" ]; then
  av_fail "--since <YYYY-MM-DD> is required"
  usage
  exit 1
fi

if ! echo "$SINCE" | grep -Eq '^[0-9]{4}-[0-9]{2}-[0-9]{2}$'; then
  av_fail "--since must be YYYY-MM-DD"
  exit 1
fi

case "$MIN_CONF" in
  low|medium|high) ;;
  *) av_fail "--min-confidence must be one of: low, medium, high (got: $MIN_CONF)"; exit 1;;
esac

REPO_ROOT=$(av_repo_root) || { av_fail "not in a git repo"; exit 1; }
LEARNINGS_FILE="$REPO_ROOT/.anvil/learnings.jsonl"

if [ ! -f "$LEARNINGS_FILE" ]; then
  av_info "no learnings recorded yet — nothing to promote" >&2
  exit 0
fi

repo_name=$(av_repo_name)
date_today=$(date -u +"%Y-%m-%d")
since_iso="${SINCE}T00:00:00Z"

# Filter + sort + group via jq. Decisions first (most durable), then other
# types alphabetical. Within each group: newest first.
filtered=$(jq -sc \
  --arg minconf "$MIN_CONF" \
  --arg since "$since_iso" \
  --arg type_filter "$TYPE_FILTER" \
  '
  def conf_rank(c):
    if c == "high" then 3
    elif c == "medium" then 2
    elif c == "low" then 1
    else 0 end;

  def ts_epoch:
    (.timestamp | fromdateiso8601? // 0);

  def type_order(t):
    if t == "decision" then 0
    elif t == "invariant" then 1
    elif t == "gotcha" then 2
    elif t == "flake" then 3
    elif t == "perf" then 4
    elif t == "cost" then 5
    elif t == "migration-shape" then 6
    else 99 end;

  (conf_rank($minconf)) as $minrank
  | ($since | fromdateiso8601) as $cutoff
  | map(select(ts_epoch >= $cutoff and conf_rank(.confidence) >= $minrank))
  | (if ($type_filter | length) > 0
     then map(select(.type == $type_filter))
     else . end)
  | group_by(.type)
  | sort_by(type_order(.[0].type))
  | map(. | sort_by(-(ts_epoch)))
  ' "$LEARNINGS_FILE")

total_count=$(echo "$filtered" | jq '[.[] | .[]] | length')

# Header. Always emitted so the operator can see "nothing matched" context.
echo "# Learnings promote — ${repo_name} (since ${SINCE}, min-confidence ${MIN_CONF})"
echo ""
echo "_Generated by \`/learn-promote\` on ${date_today}. Paste the bullets that survive your filter into your durable MEMORY.md (or per-conversation memory file)._"
echo ""

if [ "$total_count" -eq 0 ]; then
  echo "_No learnings match the filter._"
  echo ""
  echo "Try widening with \`--min-confidence medium\` or pushing \`--since\` back."
  exit 0
fi

echo "**${total_count} learning(s) match the filter.**"
echo ""

# Group + emit. Each element of $filtered is a sorted-by-type-order group
# (array of rows). Within each group: one bullet per learning + a
# "pasteable bullet" sub-line shaped for MEMORY.md.
echo "$filtered" \
  | jq -r '
    .[] | (
      "## " + (.[0].type | ascii_upcase) + "S",
      "",
      (.[] |
        "- **" + .key + "** (" + .confidence +
        (if (.prior_count // 0) > 0 then ", seen \(.prior_count + 1)x" else "" end) +
        (if .decision_type then ", " + .decision_type else "" end) +
        ") — " + .insight +
        (if ((.affected_slices // []) | length) > 0 then "\n    - affects: " + ((.affected_slices // []) | join(", ")) else "" end) +
        (if ((.files // []) | length) > 0 then "\n    - files: `" + ((.files // []) | join("`, `")) + "`" else "" end) +
        "\n    - source: " + .source_skill + " · " + (.timestamp | .[0:10]) +
        "\n    - **Pasteable bullet:** `- " + .key + " — " + (.insight | gsub("\n"; " ") | gsub("`"; "")) + "` _(promoted " + .confidence + " from .anvil/learnings.jsonl)_"
      ),
      ""
    )
  '
