#!/usr/bin/env bash
# anvil/learn — emit a MEMORY.md-compatible markdown summary on stdout.
#
# Usage:
#   learn-export.sh [--since <YYYY-MM-DD>] [--min-confidence <low|medium|high>]
#
# Use case: operator wants to optionally promote some learnings into their
# durable per-conversation MEMORY.md index. This emits a paste-ready chunk.

set -u

# Resolve ANVIL_ROOT (in order):
#   1. existing env var       — operator override
#   2. anvil-config.sh next to skills/ — post-install (any prefix; copy or symlink)
#   3. env-honoured anvil-config.sh    — $ANVIL_HOME/$CLAUDE_HOME/$HOME/.claude
#   4. relative-path fallback ($SCRIPT_DIR/../../..)  — in-checkout / dev mode
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
if [ -z "${ANVIL_ROOT:-}" ]; then
  # The script lives at <install-root>/skills/<name>/scripts/<file>.sh; the
  # config file is at <install-root>/anvil-config.sh — 3 levels up.
  _av_cfg="$SCRIPT_DIR/../../../anvil-config.sh"
  if [ -f "$_av_cfg" ]; then
    # shellcheck source=/dev/null
    . "$_av_cfg"
  fi
  unset _av_cfg
fi
if [ -z "${ANVIL_ROOT:-}" ] && [ -f "${ANVIL_HOME:-${CLAUDE_HOME:-${HOME}/.claude}}/anvil-config.sh" ]; then
  # shellcheck source=/dev/null
  . "${ANVIL_HOME:-${CLAUDE_HOME:-${HOME}/.claude}}/anvil-config.sh"
fi
if [ -z "${ANVIL_ROOT:-}" ]; then
  ANVIL_ROOT="$(cd "$SCRIPT_DIR/../../.." && pwd)"
fi
# shellcheck source=/dev/null
. "$ANVIL_ROOT/shared/lib.sh"

SINCE=""
MIN_CONF="medium"

while [ $# -gt 0 ]; do
  case "$1" in
    --since) SINCE="$2"; shift 2;;
    --min-confidence) MIN_CONF="$2"; shift 2;;
    *) av_fail "unknown arg: $1"; exit 1;;
  esac
done

REPO_ROOT=$(av_repo_root) || { av_fail "not in a git repo"; exit 1; }
LEARNINGS_FILE="$REPO_ROOT/.anvil/learnings.jsonl"

if [ ! -f "$LEARNINGS_FILE" ]; then
  av_info "no learnings recorded yet" >&2
  exit 0
fi

SINCE_ARG="null"
if [ -n "$SINCE" ]; then
  if ! echo "$SINCE" | grep -Eq '^[0-9]{4}-[0-9]{2}-[0-9]{2}$'; then
    av_fail "--since must be YYYY-MM-DD"
    exit 1
  fi
  SINCE_ARG=$(jq -n --arg s "${SINCE}T00:00:00Z" '$s')
fi

repo_name=$(av_repo_name)
date_today=$(date -u +"%Y-%m-%d")

# Emit a markdown chunk grouped by type, with a header the operator can paste.
echo "# Learnings export — ${repo_name} (as of ${date_today})"
echo ""
echo "_Generated by \`/learn export\`. Paste into your MEMORY.md if promoting these to durable memory._"
echo ""

jq -sc \
  --arg minconf "$MIN_CONF" \
  --argjson since "$SINCE_ARG" \
  '
  def conf_rank(c):
    if c == "high" then 3
    elif c == "medium" then 2
    elif c == "low" then 1
    else 0 end;

  def ts_epoch:
    (.timestamp | fromdateiso8601? // 0);

  (conf_rank($minconf)) as $minrank
  | (if $since == null then 0
     else ($since | fromdateiso8601) end) as $cutoff
  | map(select(ts_epoch >= $cutoff and conf_rank(.confidence) >= $minrank))
  | sort_by(.type, -(ts_epoch))
  | group_by(.type)
  ' "$LEARNINGS_FILE" \
| jq -r '
    .[] | (
      "## " + (.[0].type | ascii_upcase),
      "",
      (.[] |
        "- **" + .key + "** (" + .confidence + (if (.prior_count // 0) > 0 then ", seen \(.prior_count + 1)x" else "" end) + ") — " +
        .insight +
        (if (.files // []) | length > 0 then "\n    - files: `" + (.files | join("`, `")) + "`" else "" end) +
        "\n    - source: " + .source_skill + " · " + (.timestamp | .[0:10])
      ),
      ""
    )
  '
